# default_startup_script = "~/.config/sesh/scripts/default"
#
# [[startup_scripts]]
# session_path = "~/dev/Squiz"
# script_path = ""

[default_session]
name = "dotfiles"
path = "~/"

[[session]]
name = "Squiz ğŸ¢"
path = "~/dev/Squiz/"

[[session]]
name = "dotfiles âš™ï¸"
path = "~/"
startup_script = "~/.config/sesh/scripts/dotfiles_startup"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"
